#!/bin/bash

function get_full_name() {
  echo "placeholder"
}

function get_username() {
  echo "placeholder"
}

function usage() {
  echo "Initiated help"
}
while getopts h param
do
  case "${param}" in
    h) usage; exit 1;;
    *) usage; exit 1;;
  esac
done
shift ${OPTIND-1}
